/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 8b1b3df5e382e9654995abe94b91f995)
interface __BaseEnv_Env {
	IMAGES: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	CDN_DOMAIN: "httpscanner.com";
	LEAD_NOTIFICATION_TO: "pietrucha.bartosz+scanner@gmail.com";
	LEAD_NOTIFICATION_FROM: "scanner@httpscanner.com";
	POSTHOG_PROJECT_TOKEN: "phc_yMpV3BKPAbPgsHvKcEZ9Ts82pJgSJzyxJyvhqzDy3jnj";
	POSTHOG_HOST: "https://eu.i.posthog.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
