/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 70d2d180153ef5992689c4a6fe28d7c6)
interface __BaseEnv_Env {
	IMAGES: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	CDN_DOMAIN: "httpscanner.com";
	POSTHOG_PROJECT_TOKEN: string;
	POSTHOG_HOST: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
